// Screen positions follow the official 2025-11-13 guide and 2025-10-28 demo.
// These are live components; screenshots are only used by the reference viewer.
const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roman=['','Ⅰ','Ⅱ','Ⅲ','Ⅳ','Ⅴ','Ⅵ'];
export const svg=(name)=>`<svg viewBox="0 0 48 48" aria-hidden="true">${{
 back:'<path d="M30 6L12 24l18 18"/>',home:'<path d="M7 24L24 9l17 15M13 20v20h8V29h7v11h8V20"/>',
 people:'<circle cx="24" cy="12" r="5"/><circle cx="8" cy="16" r="4"/><circle cx="40" cy="16" r="4"/><path d="M15 43V24h18v19M3 38V26h9M36 26h9v12M24 25v18"/>',
 radar:'<circle cx="24" cy="24" r="19"/><circle cx="24" cy="24" r="12"/><circle cx="24" cy="24" r="4"/><path d="M24 24L40 8M4 24h9M24 4v9M44 24h-9M24 44v-9"/>',
 report:'<path d="M9 5l31 36M39 5L8 41M6 34l8 8M34 34l8 8M12 8l-3 7M36 8l3 7"/>',
 material:'<rect x="7" y="7" width="34" height="34"/><circle cx="24" cy="20" r="6"/><path d="M15 36v-6h18v6M7 16h5M36 16h5"/>',
 target:'<circle cx="24" cy="24" r="19"/><circle cx="24" cy="24" r="9"/><path d="M24 13v22M13 24h22"/>',
 crate:'<path d="M8 13l16-8 16 8v24l-16 8-16-8zM8 13l16 8 16-8M24 21v24M16 9l16 8v10"/>',
 add:'<rect x="6" y="6" width="36" height="36" rx="8"/><path d="M24 14v20M14 24h20"/>',
 freeze:'<path d="M24 4v40M7 14l34 20M7 34l34-20M17 6l7 7 7-7M17 42l7-7 7 7"/>',
 refresh:'<path d="M39 18A16 16 0 0 0 10 14M7 6v12h12M9 30a16 16 0 0 0 29 4M41 42V30H29"/>',
 check:'<rect x="8" y="8" width="32" height="32"/><path d="M14 24l7 7 14-15"/>',
 chat:'<path d="M5 7h38v27H21L10 42v-8H5zM14 20h2M23 20h2M32 20h2"/>',
 close:'<path d="M10 10l28 28M38 10L10 38"/>',
 coin:'<path d="M10 14l10 10-10 10L0 24zM30 14l10 10-10 10-10-10z"/>',
 tower:'<path d="M12 4h6v7h12V4h6v17l-7 5 5 18H14l5-18-7-5z"/>',
 search:'<circle cx="21" cy="21" r="12"/><path d="M30 30l12 12"/>',
 diamond:'<path d="M24 4l20 20-20 20L4 24zM24 16l8 8-8 8-8-8z"/>'
}[name]||''}</svg>`;
const action=(name,label,cls='',extra='')=>`<button class="${cls}" data-action="${name}" ${extra}>${label}</button>`;
export function frame(content,cls='') {return `<main class="ak-stage"><div class="ak-screen ${cls}">${content}</div></main>`;}
export function nav(title,back='homePage') {return `<nav class="ak-nav">${action(back,svg('back'),'ak-back','aria-label="返回"')}${action('homePage',svg('home'),'ak-home','aria-label="活动主页"')}${action('help','ⓘ','ak-info','aria-label="玩法说明"')}</nav>${title?`<div class="ak-screen-title">${title}</div>`:''}`;}
function logo(){return `<div class="ak-logo"><div class="ak-dot-mark">${Array.from({length:11},(_,i)=>`<div>${Array.from({length:i+1},()=>'<i></i>').join('')}</div>`).join('')}</div><b>STRONGHOLD PROTOCOL</b><span>ALLIANCE</span><h1>卫戍协议: 盟约</h1></div>`;}
export function activityHome({nickname,connected}) {
 return frame(`<div class="ak-home-art"></div><div class="ak-home-shade"></div>${nav('')}
 <span class="ak-home-tag">${connected?'PRTS 在线':'正在连接'}</span><div class="ak-account"><label for="nickname">博士</label><input id="nickname" maxlength="16" value="${esc(nickname)}" aria-label="博士代号"></div>
 ${logo()}${action('stats',`${svg('tower')}<span>成就统计</span>`,'ak-achievement')}
 <div class="ak-home-tools">${action('help',`${svg('report')}<span>S.W.E.E.P.报告</span>`,'ak-white-tool')}${action('catalog',`${svg('material')}<span>物资调配处</span>`,'ak-white-tool')}</div>
 <div class="ak-home-goals"><div class="ak-small-goals">${action('rewards',`${svg('crate')}<span>报酬说明</span>`)}${action('goals',`${svg('target')}<span>每日防卫目标</span>`)}</div>${action('goals',`${svg('target')}<span>关键目标</span>`,'ak-goal-wide')}${action('rewards',`<img src="/assets/funds.png" alt=""><div><small>LV</small><b>0</b></div><span>功勋兑换处</span>`,'ak-merit')}</div>
 <div class="ak-home-modes">${action('difficultyPage',`模拟邀约 <span>▰</span>`,'ak-difficulty-pill')}<div class="ak-mode-label"><span>♟ 独立模拟</span><span>♟♟ 同盟模拟</span></div><div class="ak-mode-row">${action('soloSetup',`${svg('people')}<b>独立模拟</b>`,'ak-mode ak-solo',connected?'':'disabled')}${action('alliancePage',`${svg('diamond')}<b>联合模拟</b>`,'ak-mode ak-coop',connected?'':'disabled')}${action('match',`${svg('radar')}<b>搜寻队友</b>`,'ak-mode ak-match',connected?'':'disabled')}</div></div>
 <button class="ak-provenance" data-action="sources">非官方同人模拟 · 素材来源</button>`, 'ak-activity');
}
export function allianceSelection({roomInput,connected,difficultyNames,difficulty}) {
 return frame(`${nav('选择同盟方式')}<div class="ak-radar"><div></div><span></span><i></i></div><div class="ak-alliance-actions"><button class="ak-create" data-action="create" ${connected?'':'disabled'}><div>${svg('add')}</div><b>创建同盟</b><small>CREATE ALLIANCE</small></button><button class="ak-difficulty-pill" data-action="difficultyPage">${difficultyNames[difficulty]} <span>▰</span></button><div class="ak-join-card"><div class="ak-key-visual">${svg('people')}<span>ALLIANCE CONNECTION</span></div><label class="ak-key-input" for="room-code">${svg('search')}<input id="room-code" maxlength="6" value="${esc(roomInput)}" placeholder="输入同盟密钥" autocomplete="off"></label>${action('join',`${svg('people')}加入同盟`,'ak-join',connected?'':'disabled')}</div></div>${action('help',`${svg('report')} 入门协议`,'ak-entry-help')}`, 'ak-tech ak-alliance');
}
export function difficultySelection({difficulty,difficultyNames,mode='solo'}) {
 return frame(`${nav('选择模拟协议',mode==='solo'?'homePage':'alliancePage')}<div class="ak-protocol-visual"><div class="ak-map-diamond"></div>${svg('radar')}<b>SIMULATION<br>PROTOCOL</b></div><div class="ak-protocols">${Object.entries(difficultyNames).map(([id,title],i)=>`<button data-action="difficultySelect" data-id="${id}" class="ak-protocol ${difficulty===id?'selected':''}"><span>${['Ⅰ','Ⅱ','Ⅲ'][i]}</span><div><b>${title}</b><small>${['STANDARD','DANGEROUS','DESPERATE'][i]} SIMULATION</small></div><i>${difficulty===id?'☑':'□'}</i></button>`).join('')}</div><div class="ak-protocol-footer">${action(mode==='solo'?'briefingPage':'alliancePage',mode==='solo'?'开始模拟':'确认协议','ak-primary')}<p>所选协议决定敌方攻势强度</p></div>`, 'ak-tech');
}
export function simulationBriefing({data,difficultyNames,difficulty}) {
 const enemy=data.enemies.at(-1);
 return frame(`${nav('1 / 2　确认本局信息','soloSetup')}<div class="ak-briefing"><h2>敌方领袖</h2><section class="ak-leader"><img src="${enemy.image}" alt="${enemy.name}"><div><b>${enemy.name}</b><small>最终攻势 / ROUND 16</small></div><span>${difficultyNames[difficulty]}</span></section><h2>核心盟约</h2><div class="ak-brief-bonds">${data.bonds.filter(b=>b.core).map(b=>`<button data-action="bond" data-id="${b.id}"><img src="${b.icon}" alt=""><span>${b.name}</span></button>`).join('')}</div><h2>附加盟约</h2><div class="ak-brief-bonds extra">${data.bonds.filter(b=>!b.core).map(b=>`<button data-action="bond" data-id="${b.id}"><img src="${b.icon}" alt=""><span>${b.name}</span></button>`).join('')}</div></div>${action('strategyPage',`${svg('check')} 准备就绪`,'ak-confirm')}`, 'ak-tech');
}
export function strategySelection({data,selectedStrategy,connected}) {
 const selected=data.strategies.find(s=>s.id===selectedStrategy);
 return frame(`${nav('2 / 2　选择策略','soloSetup')}<section class="ak-strategy-pool"><h2>策略发起人</h2><div>${data.strategies.map(s=>`<button class="ak-strategy ${s.id===selectedStrategy?'selected':''}" data-action="strategy" data-id="${s.id}" aria-pressed="${s.id===selectedStrategy}"><img src="${s.image}" alt="${s.owner}"><span>${s.owner}</span></button>`).join('')}</div></section><aside class="ak-strategy-preview"><img src="${selected.image}" alt="${selected.owner}"><h2>${selected.owner}</h2><h3>${selected.name}</h3><div class="ak-initial-hp">${svg('tower')} 初始生命 <b>${selected.hp}</b></div><p>${esc(selected.description)}</p></aside>${action('solo',`${svg('check')} 确认选择`,'ak-confirm',connected?'':'disabled')}`, 'ak-tech');
}
export function allianceLobby({state,me,data,difficultyNames}) {
 const host=me.id===state.hostId;
 return frame(`${nav('同盟模拟','leavePrompt')}<div class="ak-lobby-top"><b>同盟密钥 <span>${state.code}</span></b>${action('invite','邀请盟友　＋','ak-lobby-invite')}<span>${difficultyNames[state.difficulty]}</span></div><div class="ak-player-slots">${Array.from({length:4},(_,i)=>{const p=state.players[i];if(!p)return `<div class="ak-player-slot empty"><b>＋</b><span>等待盟友加入</span><small>ALLIANCE MEMBER 0${i+1}</small></div>`;const s=data.strategies.find(s=>s.id===p.strategy);const portrait=s.owner==='阿米娅'?data.art:data.operators.find(o=>o.name===s.owner)?.portrait||s.image;return `<article class="ak-player-slot ${p.id===me.id?'self':''}"><div class="ak-player-image"><img src="${portrait}" alt="${s.owner}"></div><small>博士 #${i+1}</small><div class="ak-player-name"><b>${esc(p.name)}</b><span>${p.id===state.hostId?'创建者':'同盟成员'}</span></div><div class="ak-player-strategy"><img src="${s.image}" alt=""><span>${s.name}</span><b>${s.hp}</b></div><p>${p.connected?'连接已建立':'正在重连'}</p></article>`}).join('')}</div><div class="ak-lobby-strategies"><span>策略选择</span>${data.strategies.map(s=>`<button data-action="strategy" data-id="${s.id}" class="${s.id===me.strategy?'selected':''}" aria-label="选择${s.name}"><img src="${s.image}" alt=""><span>${s.owner}</span></button>`).join('')}</div>${action('start',`${svg('check')}${host?'准备就绪':'等待创建者开始'}`,'ak-primary ak-lobby-ready',host?'':'disabled')}`, 'ak-tech');
}
function bondRow(p,data) {
 const bonds=data.bonds.filter(b=>p.bonds[b.name]?.count).sort((a,b)=>Number(p.bonds[b.name].active)-Number(p.bonds[a.name].active));
 return `<nav class="ak-bonds" aria-label="当前盟约">${bonds.map(b=>{const c=p.bonds[b.name];return `<button class="ak-bond ${c.active?'active':''}" data-action="bond" data-id="${b.id}" aria-label="${b.name}，${c.layers}层，${c.count}人"><div><img src="${b.icon}" alt=""><b>${c.layers}</b></div><span>${b.name}</span></button>`}).join('')}${!bonds.length?'<span class="ak-empty-bonds">部署干员激活盟约</span>':''}</nav>`;
}
function playerRail(state,v,data) {return `<nav class="ak-player-rail" aria-label="切换同盟阵地">${state.players.map(p=>`<button class="${p.id===v.id?'selected':''}" data-action="view" data-id="${p.id}" aria-label="观察${esc(p.name)}的阵地"><img src="${data.strategies.find(s=>s.id===p.strategy).image}" alt="${esc(p.name)}"><span>${svg('tower')}<b>${p.hp}</b>${state.phase==='prep'&&p.ready?'☑':''}</span><small>${esc(p.name)}</small></button>`).join('')}</nav>`;}
function reserve(p,{ops,selectedId,selectedGear,editable,me,gear}){
 const units=p.units.filter(u=>u.x===null);
 return `<section class="ak-reserve" aria-label="整备区"><div class="ak-reserve-slots">${Array.from({length:9},(_,i)=>{const u=units[i];return u?`<button class="bench-slot ${selectedId===u.id?'selected':''}" data-action="unit" data-id="${u.id}" draggable="${editable}" aria-label="选择${ops.get(u.opId).name}"><img src="${ops.get(u.opId).portrait||ops.get(u.opId).image}" alt=""><b>${roman[ops.get(u.opId).tier]}</b><span>${ops.get(u.opId).name}${u.elite?' · 精锐':''}</span></button>`:`<span class="ak-reserve-empty" aria-label="空整备位 ${i+1}"></span>`;}).join('')}</div><div class="ak-equipment">${me.equipment.map((id,i)=>`<button class="${selectedGear===i?'selected':''}" data-action="gear" data-index="${i}" ${editable?'':'disabled'} aria-label="装备${gear.get(id).name}"><img src="${gear.get(id).image}" alt=""></button>`).join('')}</div></section>`;
}
function store(p,{ops,gear,data,editable,shopOpen,phase}){
 if(!['prep','reward','won','lost'].includes(phase))return '';
 const can=editable&&!p.promotion;
 return `<section class="ak-store ${shopOpen?'expanded':'collapsed'}" aria-label="调度中心"><div class="ak-store-controls">${action('freezeAll',`${svg('freeze')} 冻结`,'ak-freeze',can?'':'disabled')}${action('refresh',`${svg('refresh')} 刷新 <b>2</b>`,'ak-refresh',can&&p.funds>=2?'':'disabled')}</div><div class="ak-store-row"><div class="ak-level-up"><span class="ak-upgrade-cost">${p.level<6?5+p.level*2:'—'}</span><div><small>LEVEL</small><b>${p.level}</b></div>${action('upgrade',p.level<6?'升级':'已满级','',can&&p.level<6&&p.funds>=5+p.level*2?'':'disabled')}${p.gearOffer?action('buyGear',`<img src="${gear.get(p.gearOffer).image}" alt="">装备 / 3`,'ak-buy-gear',can&&p.funds>=3?'':'disabled'):''}</div><div class="ak-shop-cards">${p.shop.map((slot,i)=>{if(!slot.opId)return '<div class="ak-recruited"><span>✓</span>已调度</div>';const o=ops.get(slot.opId);return `<article class="ak-shop-card tier-${o.tier} ${slot.frozen?'frozen':''}"><button class="ak-recruit" data-action="buy" data-index="${i}" aria-label="招募${o.name}，${slot.cost}资金" ${editable&&p.funds>=slot.cost?'':'disabled'}><div class="ak-shop-art"><img src="${o.portrait||o.image}" alt=""></div><span class="ak-shop-tier">${roman[o.tier]}</span><b class="ak-shop-price">${slot.cost===0?'免':slot.cost}</b><div class="ak-shop-bonds">${o.bonds.slice(0,2).map(name=>{const b=data.bonds.find(b=>b.name===name);return `<span>${b?`<img src="${b.icon}" alt="">`:''}${name}</span>`}).join('')}</div><strong><img src="/assets/class-${o.role}.png" alt="">${o.name}</strong></button>${action('freeze',svg('freeze'),'ak-card-freeze',`data-index="${i}" aria-label="${slot.frozen?'解冻':'冻结'}${o.name}" ${can?'':'disabled'}`)}</article>`;}).join('')}</div></div></section>`;
}
function unitPanel(unit,{ops,gear,editable,tab}) {
 if(!unit)return '';
 const o=ops.get(unit.opId),s=unit.stats;
 const text={trait:o.heal?'恢复攻击范围内友方干员的生命。':`${o.ground?`能够阻挡 ${s.block} 个敌人。`:'部署于高台，攻击范围内的敌人。'}${o.arts?'造成法术伤害。':'造成物理伤害。'}`,skill: `${o.heal?'治疗':'攻击'}间隔 ${s.interval.toFixed(2)} 秒，范围 ${s.range}。技能在战斗中自动开启。`,bond:o.bonds.join('、'),talent:unit.elite?'精锐状态：基础属性提升。':'集齐三名同一初始干员可晋升为精锐。'}[tab];
 return `<aside class="ak-unit-panel"><button class="ak-unit-close" data-action="deselect" aria-label="关闭干员详情">×</button><div class="ak-unit-portrait"><img src="${o.portrait||o.image}" alt="${o.name}"></div><div class="ak-unit-meta"><b>${o.name}</b><span><i>${roman[o.tier]}</i><img src="/assets/class-${o.role}.png" alt="${o.role}"> Lv.${unit.elite?2:1}</span><dl><div><dt>攻击</dt><dd>${s.atk}</dd></div><div><dt>防御</dt><dd>${s.def}</dd></div><div><dt>阻挡</dt><dd>${s.block}</dd></div><div><dt>部署</dt><dd>${o.ground?'地面':'高台'}</dd></div></dl></div><div class="ak-unit-bonds">${o.bonds.map(name=>`<span>${name}</span>`).join('')}</div><div class="ak-unit-health" id="unit-health">生命 ${s.maxHp} / ${s.maxHp}</div><nav class="ak-unit-tabs">${[['trait','特质'],['skill','技能'],['bond','盟约'],['talent','天赋']].map(([id,label])=>`<button data-action="unitTab" data-id="${id}" class="${tab===id?'selected':''}">${label}</button>`).join('')}</nav><div class="ak-unit-description"><strong>${svg('report')}作战能力</strong><p>${text}</p>${unit.gear?`<div><img src="${gear.get(unit.gear).image}" alt="">${gear.get(unit.gear).name}</div>`:''}<small>${editable?'点击有效地块部署 · R 旋转朝向':''}</small></div><div class="ak-unit-actions">${action('rotate','旋转', '',editable?'':'disabled')}${action('withdraw','撤回','',editable&&unit.x!==null?'':'disabled')}${action('sell',`出售 +${unit.elite?3:1}`,'ak-sell',editable?'':'disabled')}</div></aside>`;
}
export function battlefield({state,p,v,data,ops,gear,selectedId,selectedGear,editable,selected,shopOpen,unitTab,connected,latency,direction}) {
 const isPrep=state.phase==='prep', combat=['battle','rescue'].includes(state.phase);
 return frame(`<section class="ak-world canvas-wrap" tabindex="0" role="grid" aria-label="十列七行战场，方向键选择地块，回车部署干员"><canvas id="battlefield" width="1280" height="720" aria-hidden="true"></canvas></section>
 <div class="ak-live-hud"><button class="ak-exit" data-action="leavePrompt" aria-label="离开模拟"><svg viewBox="0 0 48 48"><path d="M36 6H9v36h27V31M20 24h25M30 15l-9 9 9 9"/></svg></button><span class="ak-link ${connected?'':'offline'}" id="hud-connection">${connected?(latency===null?'在线':latency+'ms'):'重连'}</span>${action('catalog',svg('search'),'ak-inspect','aria-label="查看干员档案"')}<div class="ak-round"><span>回合 <b>${state.round}</b></span><div class="${combat?'combat':''}">${combat?'<span id="enemy-count">作战中</span>':isPrep?'♟ 休息一下':state.phase==='reward'?'机变阶段':state.phase==='won'?'模拟完成':'模拟终止'}</div><span>${svg('tower')}<b id="view-hp">${v.hp}</b></span></div>${action('speed',`${svg('search')}▸▸`,'ak-speed',p.id===state.hostId?'':'disabled')}<div class="ak-clock"><span id="phase-time">${state.solo&&isPrep?'∞':'70'}</span><i></i></div>${isPrep?action('ready',`${svg('check')}${p.ready?'取消准备':'准备就绪'}`,'ak-ready',connected?'':'disabled'):''}${bondRow(v,data)}${playerRail(state,v,data)}</div>
 ${!combat?reserve(v,{ops,gear,selectedId,selectedGear,editable,me:p}):''}${store(p,{ops,gear,data,editable,shopOpen,phase:state.phase})}
 <div class="ak-funds-panel"><div>${svg('coin')}<b>${v.funds}</b></div><span>当前资金</span>${!combat?action('toggleShop',`${svg(shopOpen?'close':'crate')}<b>${shopOpen?'收起':'调度中心'}</b>`,'ak-store-toggle'):''}</div><span class="ak-remaining">剩余可放置角色：${Math.max(0,10-v.units.filter(u=>u.x!==null).length)}</span>
 ${unitPanel(selected,{ops,gear,editable,tab:unitTab})}${direction&&editable?`<div class="ak-direction" style="left:${direction.x-160}px;top:${Math.max(130,direction.y-130)}px" aria-label="选择部署朝向"><svg viewBox="0 0 320 260"><path d="M160 2L318 130 160 258 2 130Z"/></svg>${[['向右',0,'right'],['向下',1,'down'],['向左',2,'left'],['向上',3,'up']].map(([label,dir,cls])=>`<button class="${cls} ${selected.dir===dir?'selected':''}" data-action="face" data-dir="${dir}" aria-label="${label}部署">❯</button>`).join('')}<button class="ak-direction-cancel" data-action="cancelPlacement" aria-label="取消本次部署">×</button><span>选择干员朝向</span></div>`:''}<div class="ak-bottom-left">${action('logs',`${svg('chat')}交流`,'ak-chat')}${action('route','路线','ak-route')}${action('help','ⓘ','ak-battle-help')}</div><span class="ak-battle-context">${esc(v.name)}　/　${state.solo?'独立模拟':`同盟 ${state.code}`}　${state.speed}×</span>`, `ak-battle ${combat?'is-combat':''} ${selected?'unit-selected':''} ${shopOpen?'':'shop-hidden'}`);
}
